### ISSUE TITLE
Why the `mult` factor in the FeedForward dimension?

### ISSUE THREAD

**Issue by umbertov** [lucidrains/linformer#3]
Hi @lucidrains i've been using this module for a while, but i still haven't gotten the reason of the particular choice in this part of the code:
```python
class FeedForward(nn.Module):
    def __init__(self, dim, 
                  mult = 4,    # <-------------------------- this
                  ... ):
        ...
        self.w1 = nn.Linear(dim, dim * mult * (2 if glu else 1))
        ...
```

Why is it scaling the size hidden dimension of the FF network by 4, and is it something specific to the Linformer or is it a general best practice to have a 1:4 ratio between self-attention layer and the FF dimension? Because IIRC the Attention is All You Need  paper had the ratio 1:1.

Thanks for any anwer and for your awesome work btw!

**Comment by lucidrains** [comment]
@umbertov Hello! I set this to 4 because it was what was used in Reformer, but you're right, I've seen this varied in different architectures
