### ISSUE TITLE
Support any sequence lens

### ISSUE THREAD

**Issue by literate-goggles** [lucidrains/linformer#8]
Hi @lucidrains, Thanks for the implementation!

I just want to point out that in [the official implementation](https://github.com/facebookresearch/fairseq/blob/main/examples/linformer/linformer_src/modules/multihead_linear_attention.py#L205C19-L205C19) to support variable sequence length, they just slice the projection matrix

**Comment by lucidrains** [comment]
@systemdevart ah yea i see, that makes sense

have you tried it and does it work well?

**Comment by lucidrains** [comment]
@systemdevart ok, i added it to this unofficial repo as well
